version: '3.9'
services:
  node:
    container_name: node
    restart: always
    image: chaty-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/node/logs
    depends_on:
      - postgres
      - redis
    networks:
      - chaty_nginx_proxy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    env_file:
      - .env.development
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - chaty_nginx_proxy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    container_name: redis
    restart: always
    image: redis
    env_file:
      - .env.development
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - chaty_nginx_proxy

networks:
  chaty_nginx_proxy:
    external:
      name: chaty_nginx_proxy
